### PR TITLE
update versions for release to central

### PR DESCRIPTION
**Pull request by mikepthomas**
Upgraded the dependency versions and pushed to sonatype snapshots

You are able to get a snapshot of release 1.4.2-SNAPSHOT by adding the following to your maven pom:
```
    <dependencies>
        <dependency>
            <groupId>org.mapeditor</groupId>
            <artifactId>libtiled</artifactId>
            <version>1.4.2-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sonatype-oss</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```
[You can inspect the contents of the archives from here](https://oss.sonatype.org/#nexus-search;gav~org.mapeditor~~1.4.2-SNAPSHOT~~) 
Please let me know if you are happy with the release and I will kick off the deploy to maven central

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks @mikepthomas!

I think before we hit the release button, it would be nice to also include the just merged #2932 and to wait a bit so see if we should include #2934.

**Comment by bjorn** [comment]
@mikepthomas Seems like waiting on clarity about #2934 was a bad call. Can we just push a new version, making sure #2932 and the recent #3004 are included?

**Comment by mikepthomas** [comment]
> @mikepthomas Seems like waiting on clarity about #2934 was a bad call. Can we just push a new version, making sure #2932 and the recent #3004 are included?

I have just updated this branch with all changes in master branch of your repo and pushed another snapshot and pre-release to OSS https://oss.sonatype.org/#nexus-search;gav~org.mapeditor~libtiled~1.4.2-SNAPSHOT~jar~ it would be good to get a second pair of eyes on it to ensure its all good and when you are happy i'll get it deployed to Maven Central

**Comment by bjorn** [comment]
I'm not sure I'm a good second pair of eyes regarding Java packages. Maybe @Sam-Manflame, @hoxu or @csueiras could have a look? (sorry for the mention if you're not interested)

**Comment by bjorn** [comment]
@mikepthomas Unfortunately none of the previous contributors have responded. I've had a quick look and this version bump looks fine to me. The only thing I'm wondering regarding future version updates, is whether we can make them a little less verbose:

* The `@version` attributes seem useless to me. Maybe we can just remove them?
* I don't think we need to bump the versions of all the files in the autotests, except when something would have changed about them.
* I'm still not sure why we'd bump copyright years apart from for the changed files. And even for changed files, it would be more accurate to include the people who actually made the changes rather than bumping the year for all the listed contributors.

Anyway, again this is just for future updates. For now I've just merged this.

Please deploy this new version to Maven Central. :-)

**Comment by mikepthomas** [comment]
That all sounds good to me. The new version is now available in Maven Central https://search.maven.org/artifact/org.mapeditor/libtiled/1.4.2/jar

**Pull request merged**
