### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/tiled ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks for helping with this! I'm holding off on merging this for now, because I'm undecided on whether I will push for using OpenCollective. I don't want to direct people to multiple sites, so it would essentially mean moving away from Patreon, and currently OpenCollective does not appear to provide some features I value on Patreon, like the ability to pay with PayPal. And also at OpenCollective it looks like I would be paying a 10% fee vs. 5% fee at Patreon.

So once PayPal is supported, I want to take this up with my current patrons to see how much they would value the additional transparency, both about their contributions and my spending. And of course the option of other people than me claiming part of the available funds.

**Comment by bjorn** [comment]
Btw, it is weird that the following link:

https://opencollective.com/tiled/contributors.svg?width=890

includes a "Become a Backer" button at the end, given that it is actually the list of contributors, and clicking on it will take you do the [Contributors graph](https://github.com/bjorn/tiled/graphs/contributors). The button shouldn't be there.

**Comment by monkeywithacupcake** [comment]
Yes, that is weird. It is something that I'm looking into. I'll let you know if I get an update.

**Comment by monkeywithacupcake** [comment]
Ok, the contributors image, by default has `button=true` as an option, but we can pass `button=false`  to remove the backer button from the end.

**Pull request closed without merging**
