### PR TITLE
Rearranging Image Collection by Image Name 

### PR DESCRIPTION
**Pull request by keshav2010**
This PR is related to issue #1856

### CODE REVIEW

**Comment by hepari** [comment]
Can someone please take care of this? :) I don't understand that error message, but I need this functionality.

**Comment by hepari** [comment]
@bjorn Could you have a look at this pull request please?

**Comment by bjorn** [comment]
The main problem with this patch is that whenever some tiles in a collection tileset have the same name, only one of them will be displayed.

Personally I do not really understand the need for the name to be editable. In addition, the functionality could alternatively be implemented by using a different view for image collection tilesets (maybe QListView), which allows sorting the tiles by their image file name.

**Comment by hepari** [comment]
@bjorn : I just need the image collection be sorted by image file names, and not in the order these files were added. I'm still using the old version because that's how important it is to me. :(

**Comment by bjorn** [comment]
@hepari I'd love to help you but I am currently way too busy as I wrote about in my [latest post on Patreon](https://www.patreon.com/posts/final-home-24609471). Maybe I could have a look at this in March.

**Comment by hepari** [comment]
@bjorn I will happily wait, though it would be cool if someone could take care of it in the meantime. Good luck with the move!

**Comment by bjorn** [comment]
Now that the tiles can be manually reordered as of #2983, this change no longer really makes sense.

There could still be an option to sort the tiles by name, but it's a little unclear to me whether this should affect their stored order and how it would interact with manual reordering, so we'd need somebody with a use-case for it first.

Thanks @keshav2010 for your work in any case!

**Comment by hepari** [comment]
> 
> 
> Now that the tiles can be manually reordered as of #2983, this change no longer really makes sense.
> 
> There could still be an option to sort the tiles by name, but it's a little unclear to me whether this should affect their stored order and how it would interact with manual reordering, so we'd need somebody with a use-case for it first.
> 
> Thanks @keshav2010 for your work in any case!

I'd say it should affect the stored order and overwrite it. But I think 'reorder by file name' should be only an option for image collections, not tilesets.
(I was actually surprised to find that I now have the option to manually re-order tiles in a tileset as I never thought about it.)

The manual reordering feature makes this new version at least light-years better than the old one, so thank you for that. :)

**Comment by bjorn** [comment]
> I'd say it should affect the stored order and overwrite it. But I think 'reorder by file name' should be only an option for image collections, not tilesets.

Yeah, the only problem with this is that it's a little destructive to carefully organized tilesets, so it would have to be implemented as some manually triggered action with undo support.

**Comment by hepari** [comment]
I agree. :)

**Pull request closed without merging**
